version: "3"

services:
    tweethook:
        build:
            context: .
            dockerfile: tweethook.Dockerfile
        ## sync host directory with image directory 
        volumes:
            - ./:/tweethook
        restart: on-failure